version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current

    steps:
      - run:
          name: env install
          # command: |
          #   apt-get update
          #   apt-get install \
          #   ca-certificates \
          #   curl \
          #   gnupg \
          #   lsb-release
          #   mkdir -p /etc/apt/keyrings
          #   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          #   echo \
          #   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          #   $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo docker run hello-world

            
      - checkout
      - run:
          name: Build Dockerfile
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t smallwhitetw/backofficeweb:last .
            docker push smallwhitetw/backofficeweb:last

  test:
    docker:
      - image: smallwhitetw/backofficeweb:last

    steps:
      - checkout
      - run:
          name: runing test
          command: echo "build success"

#   deploy:
#     docker:
#       - image: circleci/node:latest
#     working_directory: ~/circleci-demo-workflows
#     steps:
#       - checkout
#       - run: sudo npm install -g npm@6
#       - run: npm install
#       - save_cache:
#           key: v1-dependencies-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#       - run: npm run build
#       - run: echo '部署开始'
#       - run: sudo apt-get update && sudo apt-get install rsync
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies
#       - add_ssh_keys:
#           fingerprints:
#             - "bd:dd:23:90:d7:86:80:d8:92:31:1b:41:09:09:27:87"
#       - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
#       - deploy:
#           name: deploy
#           command: |
#             if [ "${CIRCLE_BRANCH}" = "master" ]; then
#               rsync -avce ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/
#             else
#               echo "Not master branch, dry run only"
#             fi
#       - run: echo '部署完毕'
# workflows:
#   version: 2
#   scheduled-workflow:
#     triggers:
#       - schedule:
#           cron: "0 0 * * *"
#           filters:
#             branches:
#               only: master
    jobs:
      - build
      - test
#       - deploy