version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
        auth:
          username: smallwhitetw
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: Build Dockerfile
          command: |
            apt-get update && apt-get upgrade -y
            apt-get install -y docker.io
            docker build -t smallwhitetw/backofficeweb:last .
            docker push smallwhitetw/backofficeweb:last

  run_test:
    docker:
      - image: smallwhitetw/backofficeweb:last

    steps:
      - run:
          name: runing test
          environment:
            env: 'dev'
          command: npm run ${env}