version: 2.1
jobs:
  # build:
  #   docker:
  #     - image: docker:rc

  #   steps:
  #     - checkout
  #     - run:
  #         name: Build Dockerfile
  #         command: |
  #           docker build -t smallwhitetw/backofficeweb:last .
  #           docker push smallwhitetw/backofficeweb:last

  build:
    docker:
      - image: smallwhitetw/backofficeweb:last

    steps:
      - checkout
      - run:
          name: runing test
          command: npm run $env