version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current

    steps:
      - run:
          name: env install
          # command: |
          #   apt-get update
          #   apt-get install \
          #   ca-certificates \
          #   curl \
          #   gnupg \
          #   lsb-release
          #   mkdir -p /etc/apt/keyrings
          #   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          #   echo \
          #   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          #   $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo docker run hello-world

            
      - checkout
      - run:
          name: Build Dockerfile
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t smallwhitetw/backofficeweb:last .
            docker push smallwhitetw/backofficeweb:last

  test:
    docker:
      - image: smallwhitetw/backofficeweb:last

    steps:
      - checkout
      - run:
          name: runing test
          command: echo "build success"

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - run: echo '部署开始'
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "68:b2:76:a5:96:95:b9:c1:8c:34:33:4d:76:b5:b2:ce"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            rsync -avh ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/
      - run: echo '部署完毕'

    jobs:
      - build
      - test
      - deploy