version: 2.1
jobs:
  build:
    docker:
      - image: centos:latest

    steps:
      - run:
          name: First Step
          command: |
            echo 'Test YJ project'
            echo 'Test YJ2 project'
            ls -l